spring.application.name=02-distributed-caching
# Enable the web-based H2 console UI
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# DataSource Settings (Creates a persistent name instead of a random UUID)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA/Hibernate Properties
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6380
spring.cache.cache-names=weather